
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COMMA DICE LABEL NUMBER RANGE SEPARATORtables : table\n| tables tabletable : DICE SEPARATOR LABEL rowsrows : row\n| rows rowrow  : NUMBER SEPARATOR entries\n| RANGE SEPARATOR entriesentries : entry\n| entries COMMA entryentry : LABEL\n| NUMBER LABEL\n| DICE LABEL'
    
_lr_action_items = {'DICE':([0,1,2,4,7,8,11,12,13,15,16,17,19,20,21,22,23,],[3,3,-1,-2,-3,-4,-5,18,18,-6,-8,-10,-7,-11,18,-12,-9,]),'$end':([1,2,4,7,8,11,15,16,17,19,20,22,23,],[0,-1,-2,-3,-4,-5,-6,-8,-10,-7,-11,-12,-9,]),'SEPARATOR':([3,9,10,],[5,12,13,]),'LABEL':([5,12,13,14,18,21,],[6,17,17,20,22,17,]),'NUMBER':([6,7,8,11,12,13,15,16,17,19,20,21,22,23,],[9,9,-4,-5,14,14,-6,-8,-10,-7,-11,14,-12,-9,]),'RANGE':([6,7,8,11,15,16,17,19,20,22,23,],[10,10,-4,-5,-6,-8,-10,-7,-11,-12,-9,]),'COMMA':([15,16,17,19,20,22,23,],[21,-8,-10,21,-11,-12,-9,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'tables':([0,],[1,]),'table':([0,1,],[2,4,]),'rows':([6,],[7,]),'row':([6,7,],[8,11,]),'entries':([12,13,],[15,19,]),'entry':([12,13,21,],[16,16,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> tables","S'",1,None,None,None),
  ('tables -> table','tables',1,'p_tables','parser.py',7),
  ('tables -> tables table','tables',2,'p_tables','parser.py',8),
  ('table -> DICE SEPARATOR LABEL rows','table',4,'p_table','parser.py',15),
  ('rows -> row','rows',1,'p_rows','parser.py',19),
  ('rows -> rows row','rows',2,'p_rows','parser.py',20),
  ('row -> NUMBER SEPARATOR entries','row',3,'p_row','parser.py',27),
  ('row -> RANGE SEPARATOR entries','row',3,'p_row','parser.py',28),
  ('entries -> entry','entries',1,'p_entries','parser.py',32),
  ('entries -> entries COMMA entry','entries',3,'p_entries','parser.py',33),
  ('entry -> LABEL','entry',1,'p_entry','parser.py',40),
  ('entry -> NUMBER LABEL','entry',2,'p_entry','parser.py',41),
  ('entry -> DICE LABEL','entry',2,'p_entry','parser.py',42),
]
